### ISSUE TITLE
The ScriptApp.getProjectKey method is deprecated.

### ISSUE THREAD

**Issue by aknik** [airhadoken/twitter-lib#24] opened 2018-05-14 19:24 UTC
The ScriptApp.getProjectKey method is deprecated.
Any alternative ?

**Comment by airhadoken** [comment] 2018-05-14 19:30
Upgrade to version 23.  All uses of `getProjectKey` have been replaced with `getScriptId`, which is the non-deprecated replacement.

**Comment by airhadoken** [comment] 2018-05-15 00:50
Closing as duplicate of #15

**Closed as completed by airhadoken** 2018-05-15 00:50 UTC
